files/install-deps.yaml, packit_service_fedmsg/consumer.py
Requires https://github.com/packit-service/deployment/pull/57
Fixes https://github.com/packit-service/packit-service-fedmsg/issues/5
=> Set up sentry for fedmsg

docker-compose.yml, packit_service_fedmsg/consumer.py
Then we can remove also
https://github.com/packit-service/deployment/blob/master/openshift/packit-service-fedmsg.yml.j2#L54
=> Default REDIS_SERVICE_HOST to redis

packit_service_fedmsg/consumer.py
- Receive also messages for Koji build changes.
- Example messages:
- https://apps.fedoraproject.org/datagrepper/id?id=2020-3a2f5435-4ea6-4d6d-b6ad-36ac2bff0e02&is_raw=true&size=extra-large
- https://apps.fedoraproject.org/datagrepper/id?id=2020-76aa26dd-49e1-42f8-bf24-da1c844da510&is_raw=true&size=extra-large
=> Receive messages from koji

packit_service_fedmsg/consumer.py
via REDIS_PASSWORD env. variable.
=> Allow to specify redis password

README.md
Signed-off-by: Hunor Csomortáni <csomh@redhat.com>
=> README: rename 'master' to 'main'

CONTRIBUTING.md, Containerfile.tests, Makefile
Signed-off-by: Hunor Csomortáni <csomh@redhat.com>
=> Make the make-targets consistent in Packit

.pre-commit-config.yaml, packit_service_fedmsg/consumer.py
reverts 5261201
See also packit/deployment#226
=> Remove AWS SQS support

packit_service_fedmsg/__init__.py, packit_service_fedmsg/cli.py, packit_service_fedmsg/consumer.py, setup.py
There aren't too many left, so let's get rid of them.
Signed-off-by: Hunor Csomortáni <csomh@redhat.com>
=> Update all old-style license headers

packit_service_fedmsg/consumer.py
Needed for https://github.com/packit/hardly/issues/44
EDIT: This shouldn't affect packit service since those topics are not in `routing_keys` in `secrets/packit/[prod|stg]/fedora.toml`
They will be only in `secrets/fedora-source-git/[prod|stg]/fedora.toml`
=> Listen & react to pagure.pull-request.flag.[added|updated]

packit_service_fedmsg/consumer.py
Signed-off-by: Frantisek Lachman <flachman@redhat.com>
=> Differentiate prod and stg FAS user when filtering events

packit_service_fedmsg/consumer.py
Signed-off-by: Frantisek Lachman <flachman@redhat.com>
Related to packit/packit-service#1438
=> Use `packit-stg` FAS user in Copr for staging Packit instance

packit_service_fedmsg/consumer.py
We will process only merged PRs in packit service for koji build job.
Related to packit/packit-service#1490
Example message: https://apps.fedoraproject.org/datagrepper/v2/id?id=d5de4c69-9fda-47d1-8014-4a812c53ad97&is_raw=true&size=extra-large
=> Filter ".pagure.pull-request.closed" topic events with merged state

.gitignore, README.md, packit_service_fedmsg/consumer.py, tests/data/pr_comment.json, tests/spellbook.py, tests/test_pr_comment.py
Related with packit/packit-service#1540
=> Forward PR comment messages to celery

packit_service_fedmsg/consumer.py
For packit/packit-service#2073
=> Sent source and event_type to task.steve_jobs.process_message

Dockerfile, docker-compose.yml, files/install-deps.yaml
Related to packit/deployment#410
=> Use CentOS Stream9 as a base image

files/install-deps.yaml
[It's been in EPEL for quite some time already](https://bugzilla.redhat.com/show_bug.cgi?id=2203725#c1)
=> Install copr-messaging from RPM

.github/workflows/build-and-push.yml
You need this when there is a change in packit config schema and you want to test things in staging instance through a PR in Pagure.
=> Let manually retrigger the build and push action

packit_service_fedmsg/callbacks.py
Needed for packit/packit-service#2312
RELEASE NOTES BEGIN
N/A
RELEASE NOTES END
=> Do not check owner for Koji non-scratch builds

packit_service_fedmsg/callbacks.py, tests/data/koji_build_state_change.json, tests/test_koji.py
Fixes packit/packit-service#2367
RELEASE NOTES BEGIN
N/A
RELEASE NOTES END
=> Koji events filtering adjustments

packit_service_fedmsg/callbacks.py
Related to https://github.com/packit/packit-service/issues/2378.
=> Process org.fedoraproject.prod.buildsys.tag events

packit_service_fedmsg/callbacks.py, tests/data/openscanhub_task_finished.json, tests/test_openscanhub_task_finished.py
Related to packit/packit-service#2543
=> Add OpenScanHub task finished message
